import { NextResponse } from "next/server";
import { z } from "zod";
import { blankDay,readState,updateState } from "@/lib/store";
import { emaWeightKg } from "@/lib/calc";
import { dateSchema } from "@/lib/validation";
import candidates from "@/data/met-compendium.json";

const activityInstructions=`Analyze the activity description and any attached activity photos or tracker screenshots. Preserve the literal semantic meaning of the input. When translating another language, translate the complete phrase in context before classifying the activity; do not replace it with a similarly written, similarly pronounced, metaphorically related, or merely associated activity. Keep the output name faithful to what the user actually described.

Extract visible duration, distance, pace, steps, terrain, load, and heart rate when relevant. Split the input into distinct physical activities. First identify the real movement, event, or task independently of the table. Then use the supplied official 2024 Adult Compendium rows only as energy-reference anchors. For every described activity, choose the row with the closest physical demands; an exact activity name is not required, and the chosen row must not redefine or rename the user's activity. Match by actual movement, body position, speed, grade, resistance, load, terrain, gravity, equipment, and effort—not by shared words or loose association. Never turn a non-climbing activity into climbing simply because its name contains a word meaning ascent. Never report that an activity is unrecognized or absent from the table. Never use a resting, sitting, or 1.0 MET row as a placeholder for a physical activity. When one row is the best physical reference, use it. When the activity genuinely lies between two nearby rows for the same kind of movement, choose those two rows in base_reference_codes and use their arithmetic mean as base_met. Never combine unrelated movements or use more than two codes. Copy exact supplied codes and MET values.

Then consider only contextual details not represented by that base row, such as a light backpack, unusual resistance, surface, or environmental conditions. Express their combined effect as one adjustment_percent applied to the base row's NET active energy. Use 0 when the base row already represents the context or there is no well-supported adjustment. Explain it briefly in adjustment_rationale. Do not choose a different activity category merely because an accessory is mentioned: ordinary level walking with a backpack remains walking, not hiking/backpacking.

Do not insert a standard adjustment for load or any other context. Reason from the supplied activity, profile, heart rate, and complete reference table. Do not apply the same context twice.

Use an explicitly stated duration when present. When duration or another field is missing, you must infer the most plausible value from the user's other measurements, description, images, profile, the identity of any named route/event/task, and general knowledge about that specific activity. A named journey or complete event supplies contextual evidence: infer its actual or typical elapsed duration rather than treating duration as unavailable. If several interpretations are possible, choose the most likely one and state the uncertainty in adjustment_rationale. Show how the inference follows from this submission. Never return zero duration or zero active energy merely because duration was omitted. Do not substitute a fixed preset such as a standard 30-minute duration, one universal pace, one universal cadence, or one universal adjustment. Every inference must be specific to this input rather than a hard-coded default.

`;

export async function POST(r:Request){
  try{
    const form=await r.formData();const date=dateSchema.parse(form.get("date"));const time=String(form.get("time"));const source=String(form.get("text"));const files=form.getAll("images") as File[];
    const images=[];for(const item of files){const bytes=new Uint8Array(await item.arrayBuffer());let mime=item.type;if(bytes[0]===0xff&&bytes[1]===0xd8&&bytes[2]===0xff)mime="image/jpeg";if(bytes[0]===0x89&&bytes[1]===0x50&&bytes[2]===0x4e&&bytes[3]===0x47)mime="image/png";if(String.fromCharCode(...bytes.slice(0,6)).startsWith("GIF8"))mime="image/gif";if(String.fromCharCode(...bytes.slice(0,4))==="RIFF"&&String.fromCharCode(...bytes.slice(8,12))==="WEBP")mime="image/webp";images.push({type:"image_url",image_url:{url:`data:${mime};base64,${Buffer.from(bytes).toString("base64")}`}})}
    const state=await readState();const profile=state.profile;if(!profile)throw new Error("Save your profile before analyzing activity");const weightKg=emaWeightKg(state.days,date);if(weightKg==null)throw new Error("Log your weight before analyzing activity");const weightStr=weightKg.toFixed(1);
    const content=[{type:"text",text:`${activityInstructions}\nThe final adjusted MET is: adjusted_MET = 1 + (base_met - 1) × (1 + adjustment_percent / 100). Calculate net active energy with: active_energy_kcal = (adjusted_MET - 1) × 3.5 × ${weightStr} kg ÷ 200 × duration_minutes. Do not include resting energy. Personal context: biological sex ${profile.sex}, age ${profile.age} years, height ${profile.heightCm} cm, weight ${weightStr} kg (7-day exponential average of logged weigh-ins). Use heart rate and age only as secondary evidence when selecting effort. When the description supplies any HR for an activity, treat it as that activity's average_heart_rate_bpm even when the user does not explicitly say "average." If an HR range is supplied, use its midpoint. Return null only when no HR is supplied for that activity; never invent one.\n\nActivity description: ${source}\n\nOfficial Compendium candidates (code | MET | description):\n${candidates.rows.map(x=>`${x.code} | ${x.met} | ${x.description}`).join("\n")}`},...images];
    const schema={type:"object",additionalProperties:false,properties:{activities:{type:"array",items:{type:"object",additionalProperties:false,properties:{name:{type:"string"},duration:{type:"string"},duration_minutes:{type:"number"},average_heart_rate_bpm:{type:["number","null"]},base_reference_codes:{type:"array",items:{type:"string"}},base_met:{type:"number"},adjustment_percent:{type:"number"},adjustment_rationale:{type:"string"},active_energy_kcal:{type:"number"}},required:["name","duration","duration_minutes","average_heart_rate_bpm","base_reference_codes","base_met","adjustment_percent","adjustment_rationale","active_energy_kcal"]}}},required:["activities"]};
    const key=process.env.OPENROUTER_API_KEY;if(!key)throw new Error("OPENROUTER_API_KEY is not configured");const response=await fetch("https://openrouter.ai/api/v1/chat/completions",{method:"POST",headers:{Authorization:`Bearer ${key}`,"Content-Type":"application/json"},body:JSON.stringify({model:"openai/gpt-5.6-luna",reasoning:{effort:"xhigh"},messages:[{role:"user",content}],response_format:{type:"json_schema",json_schema:{name:"activity_analysis",strict:true,schema}}})});if(!response.ok)throw new Error(`OpenRouter error ${response.status}: ${await response.text()}`);const body=await response.json();const raw=body?.choices?.[0]?.message?.content;if(typeof raw!=="string")throw new Error("OpenRouter returned no structured content");const parsed=z.object({activities:z.array(z.object({name:z.string(),duration:z.string(),duration_minutes:z.number(),average_heart_rate_bpm:z.number().nullable(),base_reference_codes:z.array(z.string()),base_met:z.number(),adjustment_percent:z.number(),adjustment_rationale:z.string(),active_energy_kcal:z.number()}))}).parse(JSON.parse(raw));
    const now=new Date().toISOString();
    const entries=parsed.activities.map(x=>{
      const adjustedMet=1+(x.base_met-1)*(1+x.adjustment_percent/100);
      return{id:crypto.randomUUID(),name:x.name,duration:x.duration,time,durationMinutes:x.duration_minutes,met:adjustedMet,baseMet:x.base_met,adjustmentPercent:x.adjustment_percent,averageHeartRateBpm:x.average_heart_rate_bpm===null?undefined:x.average_heart_rate_bpm,compendiumCode:x.base_reference_codes.join(", "),metRationale:x.adjustment_rationale,activeEnergy:x.active_energy_kcal,sourceText:source,createdAt:now};
    });
    await updateState(s=>{const d=s.days[date]??blankDay();d.activities.push(...entries);s.days[date]=d});
    return NextResponse.json({entries});
  }catch(e){return NextResponse.json({error:e instanceof Error?e.message:"Analysis failed"},{status:400})}
}

export async function DELETE(r:Request){try{const {date,id}=await r.json();dateSchema.parse(date);if(typeof id!=="string")throw new Error("Invalid id");return NextResponse.json(await updateState(s=>{const d=s.days[date];if(d)d.activities=d.activities.filter(x=>x.id!==id)}))}catch(e){return NextResponse.json({error:e instanceof Error?e.message:"Invalid request"},{status:400})}}
export async function PATCH(r:Request){try{const {date,id,newDate,time}=await r.json();return NextResponse.json(await updateState(s=>{const source=s.days[date];if(!source)return;const index=source.activities.findIndex(entry=>entry.id===id);if(index<0)return;const [entry]=source.activities.splice(index,1);entry.time=time;const destination=s.days[newDate]??blankDay();destination.activities.push(entry);s.days[newDate]=destination}))}catch(e){return NextResponse.json({error:e instanceof Error?e.message:String(e)},{status:400})}}
