import { NextResponse } from "next/server";import { activityJsonSchema,activityResult,askOpenRouter } from "@/lib/ai";import { blankDay,readState,updateState } from "@/lib/store";import { dateSchema } from "@/lib/validation";import type { Profile } from "@/lib/types";
import { metCandidates, type MetRow } from "@/lib/met";
const prompt=(text:string,p:Profile,candidates:MetRow[])=>`Split this description into distinct physical activities. For each activity, select the single closest row from the supplied official 2024 Adult Compendium candidates. You must copy that row's exact compendium_code and MET; never invent, average, adjust, or combine MET values. Never select an inactivity/resting row for walking, swimming, exercise, or another explicitly active task. Prioritize objective pace, distance, duration, resistance, and activity type. Use heart rate and the person's age only as secondary evidence when choosing between otherwise applicable intensity rows.

Determine a realistic duration of at least 1 minute. Use an explicitly stated duration when present. Otherwise derive duration from the supplied distance or step count and the pace of the closest Compendium row. For steps, estimate distance using stride length ${Math.round(p.heightCm*(p.sex==="male"?.415:.413))/100} metres per step, then use the selected walking pace to derive time. For swimming or another distance activity, use distance and the selected row's speed; when its description gives a speed range, use the midpoint. The human-readable duration must state when it was derived. Never use a tiny placeholder duration and never say duration is indeterminable when distance or steps permit derivation.

Calculate net active energy, excluding the resting baseline during the same period, with exactly this equation: active_energy_kcal = (MET - 1) × 3.5 × ${p.weightKg} kg ÷ 200 × duration_minutes. Do not return gross calories. Personal context: biological sex ${p.sex}, age ${p.age} years, height ${p.heightCm} cm, weight ${p.weightKg} kg. Activity description: ${text}\n\nOfficial Compendium candidates (code | MET | description):\n${candidates.map(x=>`${x.code} | ${x.met} | ${x.description}`).join("\n")}\n\nReturn the compendium_code, exact MET, duration_minutes, human-readable duration, and equation result for every activity. Return JSON only.`;
export async function POST(r:Request){try{const body=await r.json();const date=dateSchema.parse(body.date);const source=String(body.text??"").trim();if(!source)throw new Error("Add an activity description");const profile=(await readState()).profile;if(!profile)throw new Error("Save your profile before analyzing activity");const candidates=metCandidates(source);if(!candidates.length)throw new Error("No matching activities were found in the MET reference table");const parsed=activityResult.parse(await askOpenRouter([{type:"text",text:prompt(source,profile,candidates)}],activityJsonSchema,"activity_analysis"));const byCode=new Map(candidates.map(x=>[x.code,x]));const now=new Date().toISOString();const entries=parsed.activities.map(x=>{const official=byCode.get(x.compendium_code);if(!official)throw new Error(`AI selected an unavailable Compendium activity code: ${x.compendium_code}`);if(x.met!==official.met)throw new Error(`AI returned the wrong MET for Compendium code ${x.compendium_code}`);return{id:crypto.randomUUID(),name:x.name,duration:x.duration,durationMinutes:x.duration_minutes,met:official.met,compendiumCode:official.code,activeEnergy:(official.met-1)*3.5*profile.weightKg/200*x.duration_minutes,sourceText:source,createdAt:now}});await updateState(s=>{const d=s.days[date]??blankDay();d.activities.push(...entries);s.days[date]=d});return NextResponse.json({entries});}catch(e){return NextResponse.json({error:e instanceof Error?e.message:"Analysis failed"},{status:400})}}
export async function DELETE(r:Request){try{const {date,id}=await r.json();dateSchema.parse(date);if(typeof id!=="string")throw new Error("Invalid id");return NextResponse.json(await updateState(s=>{const d=s.days[date];if(d)d.activities=d.activities.filter(x=>x.id!==id)}))}catch(e){return NextResponse.json({error:e instanceof Error?e.message:"Invalid request"},{status:400})}}
