import { NextResponse } from "next/server";
import { z } from "zod";
import { blankDay,updateState } from "@/lib/store";
import { dateSchema,timeSchema } from "@/lib/validation";
import { splitFoodEntry } from "@/lib/food";
import { foodAnalysisPrompt } from "@/lib/ai";

const isoDateSchema=z.string().regex(/^\d{4}-\d{2}-\d{2}$/,"Use a date in YYYY-MM-DD format").refine(value=>{const parsed=new Date(`${value}T00:00:00.000Z`);return !Number.isNaN(parsed.getTime())&&parsed.toISOString().slice(0,10)===value},"Use a valid calendar date");
const splitSchema=z.object({action:z.literal("split"),date:isoDateSchema,id:z.string().min(1),otherDate:isoDateSchema});

export async function POST(r:Request){try{
  const form=await r.formData();const date=dateSchema.parse(form.get("date"));const time=timeSchema.parse(form.get("time"));const text=String(form.get("text"));const files=form.getAll("images") as File[];
  const images=[];for(const file of files){const bytes=new Uint8Array(await file.arrayBuffer());let mime=file.type;if(bytes[0]===0xff&&bytes[1]===0xd8&&bytes[2]===0xff)mime="image/jpeg";if(bytes[0]===0x89&&bytes[1]===0x50&&bytes[2]===0x4e&&bytes[3]===0x47)mime="image/png";if(String.fromCharCode(...bytes.slice(0,6)).startsWith("GIF8"))mime="image/gif";if(String.fromCharCode(...bytes.slice(0,4))==="RIFF"&&String.fromCharCode(...bytes.slice(8,12))==="WEBP")mime="image/webp";images.push({type:"image_url",image_url:{url:`data:${mime};base64,${Buffer.from(bytes).toString("base64")}`}})}
  const schema={type:"object",additionalProperties:false,properties:{name:{type:"string",description:"Food name in the same language and script as the typed input"},amount:{type:"string",description:"Consumed amount in the same language and script as the typed input"},energy_kcal:{type:"number"}},required:["name","amount","energy_kcal"]};
  const content=[{type:"text",text:foodAnalysisPrompt(text,schema)},...images];
  const key=process.env.OPENROUTER_API_KEY;if(!key)throw new Error("OPENROUTER_API_KEY is not configured");
  const responses=await Promise.all(["google/gemini-3.7-flash","anthropic/claude-opus-5"].map(model=>fetch("https://openrouter.ai/api/v1/chat/completions",{method:"POST",headers:{Authorization:`Bearer ${key}`,"Content-Type":"application/json"},body:JSON.stringify({model,reasoning:{effort:"xhigh"},messages:[{role:"user",content}],response_format:{type:"json_schema",json_schema:{name:"food_analysis",strict:true,schema}},provider:{require_parameters:true},plugins:[{id:"response-healing"}],stream:false})})));
  const results=[];for(const response of responses){if(!response.ok)throw new Error(`OpenRouter error ${response.status}: ${await response.text()}`);const body=await response.json();const raw=body?.choices?.[0]?.message?.content;if(typeof raw!=="string")throw new Error("OpenRouter returned no structured content");results.push(z.object({name:z.string(),amount:z.string(),energy_kcal:z.number()}).parse(JSON.parse(raw)))}
  const entry={id:crypto.randomUUID(),name:results[0].name,amount:results[0].amount,energy:(results[0].energy_kcal+results[1].energy_kcal)/2,time,sourceText:text,createdAt:new Date().toISOString()};await updateState(s=>{const d=s.days[date]??blankDay();d.foods.push(entry);s.days[date]=d});return NextResponse.json(entry);
}catch(e){return NextResponse.json({error:e instanceof Error?e.message:String(e)},{status:400})}}
export async function DELETE(r:Request){try{const {date,id}=await r.json();dateSchema.parse(date);if(typeof id!=="string")throw new Error("Invalid id");return NextResponse.json(await updateState(s=>{const d=s.days[date];if(d)d.foods=d.foods.filter(x=>x.id!==id)}))}catch(e){return NextResponse.json({error:e instanceof Error?e.message:"Invalid request"},{status:400})}}
export async function PATCH(r:Request){try{const body=await r.json();if(body?.action==="split"){const {date,id,otherDate}=splitSchema.parse(body);if(otherDate===date)throw new Error("Choose a different day for the other half");return NextResponse.json(await updateState(s=>{const source=s.days[date];if(!source)throw new Error("Food entry not found");const index=source.foods.findIndex(entry=>entry.id===id);if(index<0)throw new Error("Food entry not found");const [firstHalf,secondHalf]=splitFoodEntry(source.foods[index],crypto.randomUUID());source.foods[index]=firstHalf;const destination=s.days[otherDate]??blankDay();destination.foods.push(secondHalf);s.days[otherDate]=destination}))}const {date,id,newDate,time,userTasteScore}=body;return NextResponse.json(await updateState(s=>{const source=s.days[date];if(!source)return;const index=source.foods.findIndex(entry=>entry.id===id);if(index<0)return;if(typeof userTasteScore==="number"){source.foods[index].userTasteScore=Math.max(1,Math.min(10,Math.round(userTasteScore)));return}const [entry]=source.foods.splice(index,1);entry.time=time;const destination=s.days[newDate]??blankDay();destination.foods.push(entry);s.days[newDate]=destination}))}catch(e){return NextResponse.json({error:e instanceof Error?e.message:String(e)},{status:400})}}
