import { NextResponse } from "next/server";
import { z } from "zod";
import { blankDay,readState,updateState } from "@/lib/store";
import type { State } from "@/lib/types";
import { dateSchema,timeSchema } from "@/lib/validation";
import { duplicateFoodEntry,foodEstimateEnergy,foodEstimateSchema,foodPriceFromText,splitFoodEntry } from "@/lib/food";
import { foodAnalysisPrompt } from "@/lib/ai";

const isoDateSchema=z.string().regex(/^\d{4}-\d{2}-\d{2}$/,"Use a date in YYYY-MM-DD format").refine(value=>{const parsed=new Date(`${value}T00:00:00.000Z`);return !Number.isNaN(parsed.getTime())&&parsed.toISOString().slice(0,10)===value},"Use a valid calendar date");
const splitSchema=z.object({action:z.literal("split"),date:isoDateSchema,id:z.string().min(1),otherDate:isoDateSchema});

function submissionResponse(state:State,id:string){
 for(const day of Object.values(state.days)){
  const entry=day.foods.find(food=>food.id===id);
  if(entry)return NextResponse.json(entry);
 }
 return NextResponse.json({error:"This food submission was already saved and later deleted. Refresh the tracker before adding it again."},{status:409});
}

export async function POST(r:Request){try{
  const form=await r.formData();const date=dateSchema.parse(form.get("date"));const time=timeSchema.parse(form.get("time"));const text=String(form.get("text")??"");const priceValue=form.get("price");const explicitPrice=priceValue==null||priceValue===""?foodPriceFromText(text):z.number().finite().nonnegative().parse(Number(priceValue));const files=form.getAll("images") as File[];
  const submissionId=z.uuid().parse(form.get("submissionId")??crypto.randomUUID());
  const mutationId=`food:${submissionId}`;
  if(!text.trim()&&!files.length)throw new Error("Describe your meal or add a photo before submitting.");
  const saved=await readState();
  if(saved.appliedMutationIds?.includes(mutationId))return submissionResponse(saved,submissionId);
  const images=[];for(const file of files){const bytes=new Uint8Array(await file.arrayBuffer());let mime=file.type;if(bytes[0]===0xff&&bytes[1]===0xd8&&bytes[2]===0xff)mime="image/jpeg";if(bytes[0]===0x89&&bytes[1]===0x50&&bytes[2]===0x4e&&bytes[3]===0x47)mime="image/png";if(String.fromCharCode(...bytes.slice(0,6)).startsWith("GIF8"))mime="image/gif";if(String.fromCharCode(...bytes.slice(0,4))==="RIFF"&&String.fromCharCode(...bytes.slice(8,12))==="WEBP")mime="image/webp";images.push({type:"image_url",image_url:{url:`data:${mime};base64,${Buffer.from(bytes).toString("base64")}`}})}
  const schema={type:"object",additionalProperties:false,properties:{name:{type:"string",description:"Food name in the same language and script as the typed input"},amount:{type:"string",description:"Consumed amount in the same language and script as the typed input"},price:{type:["number","null"],minimum:0,description:"Actual total paid price visible in the receipt, delivery-app screenshot, menu, or typed description; null if absent. Never estimate a price."},items:{type:"array",minItems:1,items:{type:"object",additionalProperties:false,properties:{name:{type:"string"},price:{type:["number","null"],minimum:0,description:"The price explicitly shown for this food line on a receipt or order breakdown; null if there is no itemized price. Never allocate, estimate, or divide a total."},grams:{type:"number",minimum:0},kcal_per_100g:{type:"number",minimum:0},kcal:{type:"number",minimum:0},protein_g:{type:"number",minimum:0},carbs_g:{type:"number",minimum:0},fat_g:{type:"number",minimum:0},sodium_mg:{type:"number",minimum:0},confidence:{type:"string",enum:["high","medium","low"]}},required:["name","price","grams","kcal_per_100g","kcal","protein_g","carbs_g","fat_g","sodium_mg","confidence"]}},total_kcal:{type:"number",minimum:0},total_range:{type:"array",minItems:2,maxItems:2,items:{type:"number",minimum:0}},macros:{type:"object",additionalProperties:false,properties:{protein_g:{type:"number",minimum:0},carbs_g:{type:"number",minimum:0},fat_g:{type:"number",minimum:0}},required:["protein_g","carbs_g","fat_g"]},sodium_mg:{type:"number",minimum:0},salt_g:{type:"number",minimum:0}},required:["name","amount","price","items","total_kcal","total_range","macros","sodium_mg","salt_g"]};
  const content=[{type:"text",text:foodAnalysisPrompt(text,schema)},...images];
  const key=process.env.OPENROUTER_API_KEY;if(!key)throw new Error("OPENROUTER_API_KEY is not configured");
  const analyze=async()=>{const response=await fetch("https://openrouter.ai/api/v1/chat/completions",{method:"POST",headers:{Authorization:`Bearer ${key}`,"Content-Type":"application/json"},body:JSON.stringify({model:"openai/gpt-5.6-sol",reasoning:{effort:"xhigh"},messages:[{role:"user",content}],response_format:{type:"json_schema",json_schema:{name:"food_analysis",strict:true,schema}},provider:{require_parameters:true},plugins:[{id:"response-healing"}],stream:false})});if(!response.ok)throw new Error(`OpenRouter error ${response.status}: ${await response.text()}`);const body=await response.json();const raw=body?.choices?.[0]?.message?.content;if(typeof raw!=="string")throw new Error("OpenRouter returned no structured content");return foodEstimateSchema.parse(JSON.parse(raw))};
  let estimate;try{estimate=await analyze()}catch(firstError){try{estimate=await analyze()}catch{throw firstError}}
  const price=explicitPrice??(typeof estimate.price==="number"&&Number.isFinite(estimate.price)&&estimate.price>=0?estimate.price:undefined);const entry={id:submissionId,name:estimate.name,amount:estimate.amount,energy:foodEstimateEnergy(estimate),price,items:estimate.items.map(item=>({name:item.name,price:typeof item.price==="number"?item.price:undefined,grams:item.grams,kcalPer100g:item.kcal_per_100g,energy:item.kcal,proteinG:item.protein_g,carbsG:item.carbs_g,fatG:item.fat_g,sodiumMg:item.sodium_mg,confidence:item.confidence})),energyRange:estimate.total_range,macros:{proteinG:estimate.macros.protein_g,carbsG:estimate.macros.carbs_g,fatG:estimate.macros.fat_g},sodiumMg:estimate.sodium_mg,saltG:estimate.salt_g,time,sourceText:text,createdAt:new Date().toISOString()};const state=await updateState(s=>{const d=s.days[date]??blankDay();d.foods.push(entry);s.days[date]=d},mutationId);return submissionResponse(state,submissionId);
}catch(e){return NextResponse.json({error:e instanceof Error?e.message:String(e)},{status:400})}}
export async function DELETE(r:Request){try{const {date,id}=await r.json();dateSchema.parse(date);if(typeof id!=="string")throw new Error("Invalid id");return NextResponse.json(await updateState(s=>{const d=s.days[date];if(d)d.foods=d.foods.filter(x=>x.id!==id)}))}catch(e){return NextResponse.json({error:e instanceof Error?e.message:"Invalid request"},{status:400})}}
export async function PATCH(r:Request){try{const body=await r.json();if(body?.action==="split"){const {date,id,otherDate}=splitSchema.parse(body);if(otherDate===date)throw new Error("Choose a different day for the other half");return NextResponse.json(await updateState(s=>{const source=s.days[date];if(!source)throw new Error("Food entry not found");const index=source.foods.findIndex(entry=>entry.id===id);if(index<0)throw new Error("Food entry not found");const [firstHalf,secondHalf]=splitFoodEntry(source.foods[index],crypto.randomUUID());source.foods[index]=firstHalf;const destination=s.days[otherDate]??blankDay();destination.foods.push(secondHalf);s.days[otherDate]=destination}))}const {date,id,newDate,time,userTasteScore,userTasteNote}=body;return NextResponse.json(await updateState(s=>{const source=s.days[date];if(!source)return;const index=source.foods.findIndex(entry=>entry.id===id);if(index<0)return;if(body?.action==="duplicate"){source.foods.splice(index+1,0,duplicateFoodEntry(source.foods[index],crypto.randomUUID()));return}if(typeof userTasteScore==="number")source.foods[index].userTasteScore=Math.max(1,Math.min(10,Math.round(userTasteScore)));if(typeof userTasteNote==="string"){source.foods[index].userTasteNote=userTasteNote.trim().slice(0,500);return}if(typeof userTasteScore==="number")return;const [entry]=source.foods.splice(index,1);entry.time=time;const destination=s.days[newDate]??blankDay();destination.foods.push(entry);s.days[newDate]=destination}))}catch(e){return NextResponse.json({error:e instanceof Error?e.message:String(e)},{status:400})}}
