"use client";
import {useEffect,useState} from "react";
import {Bar,BarChart,CartesianGrid,Cell,Line,LineChart,ReferenceLine,ResponsiveContainer,Tooltip,XAxis,YAxis} from "recharts";
import type {Day,MedicationDefinition,MedicationEntry,Profile,State} from "@/lib/types";
import {dailyWeight,dayKey,dayMetrics,emaEndingAt,emaWeightKg,latestWeightKg} from "@/lib/calc";
const pageOpenedAt=new Date();
const pageOpenedDate=dayKey(pageOpenedAt);
const pageOpenedTime=`${String(pageOpenedAt.getHours()).padStart(2,"0")}:${String(pageOpenedAt.getMinutes()).padStart(2,"0")}`;
const localTime=pageOpenedTime;
type UnitMode="tnt"|"kcal";
const THEMES=[{value:"garden",label:"Garden"},{value:"paper",label:"Paper"},{value:"midnight",label:"Midnight"},{value:"ocean",label:"Ocean"},{value:"blossom",label:"Blossom"},{value:"slate",label:"Slate"},{value:"contrast",label:"High contrast"}];
type BusyActions=ReadonlySet<string>;
type RunAction=(name:string,action:()=>Promise<unknown>)=>void;
const C4_TNT_FACTOR=1.34;
const KCAL_TO_KWH=0.001162222;
const KCAL_TO_JOULES=4184;
const fmt=(n:number|null,signed=false,mode:UnitMode="tnt")=>{if(n==null)return "—";const prefix=signed&&n>=0?"+":"";if(mode==="kcal")return `${prefix}${Math.round(n).toLocaleString()} kcal`;const tnt=Math.round(n).toLocaleString();const c4=Math.round(n/C4_TNT_FACTOR).toLocaleString();return `${prefix}${tnt} g TNT\n${prefix}${c4} g C4`};
const summaryFmt=(n:number|null,signed=false,mode:UnitMode="tnt")=>n==null?"—":`${fmt(n,signed,mode)}\n${signed&&n>=0?"+":""}${Math.round(n*KCAL_TO_KWH*315).toLocaleString()} k tokens`;
const currentTime=()=>{const now=new Date();return `${String(now.getHours()).padStart(2,"0")}:${String(now.getMinutes()).padStart(2,"0")}`};
const readLocal=(key:string)=>{try{return window.localStorage.getItem(key)}catch{return null}};
const writeLocal=(key:string,value:string)=>{try{window.localStorage.setItem(key,value)}catch{}};
async function request<T=unknown>(url:string,init?:RequestInit):Promise<T>{const response=await fetch(url,init);const text=await response.text();let body:unknown={};if(text){try{body=JSON.parse(text)}catch{if(!response.ok)throw new Error(`Request failed (${response.status})`);throw new Error("The server returned an invalid response")}}if(!response.ok)throw new Error(typeof body==="object"&&body!==null&&"error" in body&&typeof body.error==="string"?body.error:`Request failed (${response.status})`);return body as T}
async function resizeImageForUpload(file:File,maxSide=1024):Promise<File>{const bitmap=await createImageBitmap(file,{imageOrientation:"from-image"});try{const longest=Math.max(bitmap.width,bitmap.height);if(longest<=maxSide)return file;const scale=maxSide/longest;const canvas=document.createElement("canvas");canvas.width=Math.max(1,Math.round(bitmap.width*scale));canvas.height=Math.max(1,Math.round(bitmap.height*scale));const context=canvas.getContext("2d");if(!context)throw new Error("Image resizing is not supported by this browser");context.fillStyle="#fff";context.fillRect(0,0,canvas.width,canvas.height);context.drawImage(bitmap,0,0,canvas.width,canvas.height);const blob=await new Promise<Blob>((resolve,reject)=>canvas.toBlob(value=>value?resolve(value):reject(new Error(`Could not resize ${file.name}`)),"image/jpeg",.86));const stem=file.name.replace(/\.[^.]+$/,"")||"image";return new File([blob],`${stem}.jpg`,{type:"image/jpeg",lastModified:file.lastModified})}finally{bitmap.close()}}
async function appendUploadImages(form:FormData,images:File[]){const resized=await Promise.all(images.map(image=>resizeImageForUpload(image)));resized.forEach(image=>form.append("images",image))}
export default function Home(){
 const [state,setState]=useState<State>({profile:null,days:{},medicationList:[]}),[date,setDate]=useState(pageOpenedDate),[error,setError]=useState(""),[pending,setPending]=useState<Set<string>>(()=>new Set()),[style,setStyle]=useState("garden"),[unitMode,setUnitMode]=useState<UnitMode>("tnt");
 const load=()=>request<State>("/api/state").then(setState).catch(e=>setError(e.message));useEffect(()=>{request<State>("/api/state").then(setState).catch(e=>setError(e.message));if(readLocal("energy-unit")==="kcal")setUnitMode("kcal");const savedStyle=readLocal("energy-theme");if(savedStyle&&THEMES.some(theme=>theme.value===savedStyle))setStyle(savedStyle)},[]);
 const day=state.days[date];const activityEstimate=(()=>{if(day?.activities.length)return null;const values:number[]=[];const base=new Date(date+"T12:00:00");for(let i=1;i<=7;i++){const x=new Date(base);x.setDate(x.getDate()-i);const key=dayKey(x);const activities=state.days[key]?.activities;if(activities?.length)values.push(activities.reduce((sum,a)=>sum+a.activeEnergy,0))}return values.length?{value:values.reduce((sum,n)=>sum+n,0)/values.length,count:values.length}:null})();const estimated=activityEstimate!=null;const calculated=dayMetrics(state.profile,emaWeightKg(state.days,date),day,activityEstimate?.value);const provisional=calculated.tracker==null&&calculated.aiBurn!=null;const burnEstimated=estimated||provisional;const m=calculated.blended==null&&calculated.aiBurn!=null?{...calculated,blended:calculated.aiBurn,balance:calculated.intake-calculated.aiBurn}:calculated;
 const chart=(()=>{const out=[];const base=new Date(date+"T12:00:00");for(let i=29;i>=0;i--){const x=new Date(base);x.setDate(x.getDate()-i);const key=dayKey(x);const chartDay=state.days[key];const isSelected=key===date;const mm=isSelected?m:dayMetrics(state.profile,emaWeightKg(state.days,key),chartDay);const isEstimated=isSelected&&burnEstimated;out.push({date:key.slice(5),intake:mm.intake,burn:isEstimated?null:mm.blended,balance:isEstimated?null:mm.balance,estimated:isEstimated,recorded:!!chartDay&&(chartDay.foods.length>0||chartDay.activities.length>0||chartDay.trackerBurn!=null)})}const first=out.findIndex(x=>x.recorded);return first<0?[]:out.slice(first)})();
 const weightChart=(()=>{const out:{date:string,daily:number|null,average:number|null,recorded:boolean}[]=[];const base=new Date(date+"T12:00:00");for(let i=29;i>=0;i--){const current=new Date(base);current.setDate(current.getDate()-i);const key=dayKey(current);const daily=dailyWeight(state.days[key]);const average=emaEndingAt(state.days,current);out.push({date:key.slice(5),daily,average,recorded:daily!=null})}const first=out.findIndex(point=>point.recorded);return first<0?[]:out.slice(first)})();
 const lastWeight=latestWeightKg(state.days);
 const busyFor=(name:string)=>pending.has(name)?name:"";
 async function run(name:string,fn:()=>Promise<unknown>){setPending(current=>new Set(current).add(name));setError("");try{await fn();await load()}catch(e){setError(e instanceof Error?e.message:"Something went wrong")}finally{setPending(current=>{const next=new Set(current);next.delete(name);return next})}}
 const changeUnitMode=(mode:UnitMode)=>{setUnitMode(mode);writeLocal("energy-unit",mode)};
 const changeStyle=(next:string)=>{setStyle(next);writeLocal("energy-theme",next)};
 return <div className={`appShell theme-${style}`}><main><header><div><span className="eyebrow">DAILY ENERGY LEDGER</span><h1>Fuel <i>&</i> Motion</h1><p>Many units. A clearer picture of what comes in and what moves out.</p></div><div className="headerControls"><label>Style<select value={style} onChange={e=>changeStyle(e.target.value)}>{THEMES.map(theme=><option key={theme.value} value={theme.value}>{theme.label}</option>)}</select></label><label>Energy units<select value={unitMode} onChange={e=>changeUnitMode(e.target.value as UnitMode)}><option value="tnt">TNT + C4</option><option value="kcal">Calories (kcal)</option></select></label><label className="date">Selected day<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label></div></header>
 {error&&<div className="error" role="alert">{error}<button onClick={()=>setError("")}>×</button></div>}
 <section className="metrics">
  <Metric label="Food intake" value={summaryFmt(m.intake,false,unitMode)} tone="lime"/><Metric label="Minimal daily baseline" value={summaryFmt(m.baselineBurn,false,unitMode)} sub="RMR × 1.20; walking excluded"/><Metric label="Active movement" value={summaryFmt(m.activity,false,unitMode)} sub={activityEstimate?`Estimated from ${activityEstimate.count} prior day${activityEstimate.count===1?"":"s"}; baseline excluded`:"Net activity; baseline excluded"} estimated={estimated}/>
  <Metric label="Corrected tracker" value={summaryFmt(m.tracker,false,unitMode)} sub={day?.trackerBurn!=null?`${day.trackerBurn} × ${day.correctionFactor}`:"Needs tracker input"}/><Metric label="Blended burn" value={summaryFmt(m.blended,false,unitMode)} tone="teal" sub={provisional?"Provisional AI burn":estimated?"Includes estimated activity":undefined} estimated={burnEstimated}/><Metric label="How much you can still eat" value={summaryFmt(m.balance==null?null:-m.balance,false,unitMode)} tone={m.balance!=null&&m.balance>0?"warm":"blue"} sub={provisional?"Provisional AI burn minus food eaten":estimated?"Estimated burn minus food eaten":"Burn minus food eaten"} estimated={burnEstimated}/>
 </section>
 <p className="activityNetNote"><b>Activity is above rest:</b> baseline energy during each activity is subtracted, then the daily baseline is counted separately once.</p>
 <section className="grid"><div className="stack"><ProfileCard profile={state.profile} busy={busyFor("profile")} save={p=>run("profile",()=>request("/api/profile",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(p)}))}/><WeightCard date={date} day={day} lastWeight={lastWeight} busy={busyFor("weight")} run={run}/><FoodCard date={date} day={day} busy={busyFor("food")} run={run} unitMode={unitMode} allDays={state.days}/><ActivityCard date={date} day={day} busy={busyFor("activity")} run={run} unitMode={unitMode}/><MedicationCard date={date} day={day} saved={state.medicationList} pending={pending} run={run}/><DataCard pending={pending} run={run}/></div>
 <div className="stack"><BurnCard date={date} day={day} metrics={m} busy={busyFor("burn")} run={run} unitMode={unitMode}/><WeightChart data={weightChart}/><Chart data={chart} unitMode={unitMode}/><BalanceChart data={chart} unitMode={unitMode}/></div></section>
 <EnergyTable metrics={m} unitMode={unitMode}/>
 </main></div>
}
function Metric({label,value,sub,tone="",estimated=false}:{label:string,value:string,sub?:string,tone?:string,estimated?:boolean}){return <article className={`metric ${tone} ${estimated?"estimated":""}`}><small>{label}{estimated&&" · ESTIMATED"}</small><strong>{value}</strong>{sub&&<span>{sub}</span>}</article>}
function DataCard({pending,run}:{pending:BusyActions,run:RunAction}){
 const [message,setMessage]=useState("");
 const exportData=()=>run("backup-export",async()=>{setMessage("");const response=await fetch("/api/backup");if(!response.ok){const body=await response.json();throw new Error(body.error||"Export failed")}const blob=await response.blob();const match=response.headers.get("Content-Disposition")?.match(/filename="([^"]+)"/);const url=URL.createObjectURL(blob);const link=document.createElement("a");link.href=url;link.download=match?.[1]??`fuel-and-motion-${dayKey(new Date())}.json`;document.body.appendChild(link);link.click();link.remove();URL.revokeObjectURL(url);setMessage("Backup downloaded.")});
 const importData=(file:File,input:HTMLInputElement)=>{if(!window.confirm("Import this backup? It will replace all current profile, daily, weight, food, activity, tracker, and medication data.")){input.value="";return}run("backup-import",async()=>{setMessage("");try{const response=await fetch("/api/backup",{method:"PUT",headers:{"Content-Type":"application/json"},body:await file.text()});const body=await response.json();if(!response.ok)throw new Error(body.error||"Import failed");setMessage("Backup imported. All views now use the restored data.")}finally{input.value=""}})};
 return <Card title="Data & backup" number="07" note="Move or restore every saved record with one JSON file"><div className="backupActions"><button type="button" onClick={exportData} disabled={pending.has("backup-export")||pending.has("backup-import")}>{pending.has("backup-export")?"Preparing…":"Export all data"}</button><label className="upload backupImport">{pending.has("backup-import")?"Importing…":"Import backup"}<input hidden type="file" accept="application/json,.json" disabled={pending.has("backup-export")||pending.has("backup-import")} onChange={event=>{const file=event.currentTarget.files?.[0];if(file)importData(file,event.currentTarget)}}/></label></div><p className="backupNote">Import replaces the current dataset after validating the file. Export first if you may need to undo it.</p>{message&&<p className="backupSuccess" role="status">{message}</p>}</Card>
}
function ProfileCard({profile,busy,save}:{profile:Profile|null,busy:string,save:(p:Profile)=>void}){const [sex,setSex]=useState(profile?.sex??""),[age,setAge]=useState(profile?.age?.toString()??""),[height,setHeight]=useState(profile?.heightCm?.toString()??"");useEffect(()=>{setSex(profile?.sex??"");setAge(profile?.age?.toString()??"");setHeight(profile?.heightCm?.toString()??"")},[profile]);return <Card title="Your baseline" number="01" note="Used for every date; weight comes from your logs"><form className="form profile" onSubmit={e=>{e.preventDefault();save({sex,age:Number(age),heightCm:Number(height)})}}><label>Biological sex<input value={sex} onChange={e=>setSex(e.target.value)}/></label><label>Age<input type="number" value={age} onChange={e=>setAge(e.target.value)}/></label><label>Height <span>cm</span><input type="number" value={height} onChange={e=>setHeight(e.target.value)}/></label><button disabled={busy==="profile"}>{busy==="profile"?"Saving…":"Save profile"}</button></form></Card>}
function WeightCard({date,day,lastWeight,busy,run}:{date:string,day?:Day,lastWeight:number|null,busy:string,run:(n:string,f:()=>Promise<unknown>)=>void}){const [weight,setWeight]=useState(lastWeight?.toString()??""),[time,setTime]=useState(localTime);useEffect(()=>{setWeight(lastWeight?.toString()??"")},[lastWeight]);const entries=day?.weights??[];const average=entries.length?entries.reduce((sum,entry)=>sum+entry.weightKg,0)/entries.length:null;return <Card title="Weight" number="02" note="All weight-based math uses the 7-day EMA of these logs"><form className="weightForm" onSubmit={event=>{event.preventDefault();run("weight",async()=>{await request("/api/weight",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({date,time,weightKg:Number(weight)})})})}}><label>Weight <span>kg</span><input type="number" step=".01" value={weight} onChange={event=>setWeight(event.target.value)}/></label><label>Time<input type="time" value={time} onChange={event=>setTime(event.target.value)}/></label><button className="primary" disabled={busy==="weight"}>{busy==="weight"?"Saving…":"Log weight"}</button></form>{average!=null&&<p className="dailyWeightAverage">Daily average: <b>{average.toFixed(2)} kg</b></p>}{entries.length?<div className="entries weightEntries">{entries.map(entry=><div key={entry.id}><span><b>{entry.weightKg.toFixed(2)} kg</b><small>{entry.time}</small></span><button onClick={()=>window.confirm(`Delete ${entry.weightKg.toFixed(2)} kg?`)&&run("delete",()=>request("/api/weight",{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({date,id:entry.id})}))} aria-label={`Delete ${entry.weightKg.toFixed(2)} kg`}>×</button></div>)}</div>:<p className="empty">No weight recorded for this day.</p>}</Card>}
function FoodRating({userTaste,onRate}:{userTaste?:number,onRate:(score:number)=>void}){return <div className="foodRating"><div className="ratingRow"><small>How did it taste?{userTaste!=null?` ${userTaste}/10`:""}</small></div><div className="tasteStars">{[1,2,3,4,5,6,7,8,9,10].map(n=><button key={n} type="button" className={`starBtn${userTaste!=null&&n<=userTaste?" active":""}`} onClick={()=>onRate(n)} aria-label={`Rate taste ${n}/10`}>{n}</button>)}</div></div>}
function FoodSuggestions({allFoods}:{allFoods:{name:string,userTasteScore?:number}[]}){const [suggestions,setSuggestions]=useState<{name:string,why_healthy:string,why_youd_like_it:string,predicted_taste_score:number}[]>([]),[loading,setLoading]=useState(false),[error,setError]=useState("");const generate=async()=>{setLoading(true);setError("");try{const result=await request<{suggestions:typeof suggestions}>("/api/food-suggestions",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({history:allFoods})});setSuggestions(result.suggestions)}catch(e){setError(e instanceof Error?e.message:"Failed to get suggestions")}finally{setLoading(false)}};return <div className="foodSuggestions"><div><h3>Healthy foods you&apos;d like</h3><p>Based on your taste ratings across all logged days — rate more foods for better picks.</p></div><button onClick={generate} disabled={loading}>{loading?"Finding foods…":"Suggest healthy foods"}</button>{error&&<p className="factError" role="alert">{error}</p>}{suggestions.length>0&&<div className="suggestionGrid">{suggestions.map((s,i)=><div key={i} className="suggestionItem"><b>{s.name}</b><div className="suggestionScores"><span className="scoreTaste">You&apos;d rate it ~{s.predicted_taste_score}/10</span></div><small>{s.why_healthy}</small><small className="tastNote">{s.why_youd_like_it}</small></div>)}</div>}</div>}
function FoodCard({date,day,busy,run,unitMode,allDays}:{date:string,day?:Day,busy:string,run:(n:string,f:()=>Promise<unknown>)=>void,unitMode:UnitMode,allDays:Record<string,Day>}){const [text,setText]=useState(""),[time,setTime]=useState(localTime),[images,setImages]=useState<File[]>([]);const add=(files:File[])=>setImages(v=>[...v,...files.filter(f=>f.type.startsWith("image/"))]);const allFoods=Object.values(allDays).flatMap(d=>d.foods.map(f=>({name:f.name,userTasteScore:f.userTasteScore})));const rateTaste=(id:string,score:number)=>run(`rate-${id}`,()=>request("/api/food",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({date,id,userTasteScore:score})}));return <Card title="Food intake" number="02" note="Text, photos, or both"><form onSubmit={e=>{e.preventDefault();run("food",async()=>{const f=new FormData();f.set("date",date);f.set("time",time);f.set("text",text);await appendUploadImages(f,images);await request("/api/food",{method:"POST",body:f});setText("");setImages([])})}}><label>Meal time<input type="time" value={time} onChange={e=>setTime(e.target.value)} required/></label><textarea value={text} onChange={e=>setText(e.target.value)} onPaste={e=>add([...e.clipboardData.files])} placeholder="Describe your meal, or paste an image here…"/><label className="upload">＋ Add food photos<input hidden multiple type="file" accept="image/jpeg,image/png,image/webp,image/gif" onChange={e=>add([...e.target.files??[]])}/></label>{images.length>0&&<div className="previews">{images.map((f,i)=><figure key={i}><img src={URL.createObjectURL(f)} alt="Food preview"/><button type="button" onClick={()=>setImages(x=>x.filter((_,j)=>j!==i))}>×</button></figure>)}</div>}<button className="primary" disabled={busy==="food"}>{busy==="food"?"Analyzing…":"Analyze food →"}</button></form>{day?.foods.map(x=><div key={x.id} className="foodEntryWithRating"><div className="foodEntryMain"><span><b>{x.name}</b><small>{x.time?`${x.time} · `:""}{x.amount}</small></span><strong>{fmt(x.energy,false,unitMode)}</strong>{<button onClick={()=>changeEntryDateTime("/api/food",date,x.id,x.time??"",run)} aria-label={`Change date and time for ${x.name}`}>✎</button>}<button onClick={()=>window.confirm(`Delete ${x.name}?`)&&run("delete",()=>request("/api/food",{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({date,id:x.id})}))} aria-label={`Delete ${x.name}`}>×</button></div><FoodRating userTaste={x.userTasteScore} onRate={score=>rateTaste(x.id,score)}/></div>)}{(!day?.foods.length)&&<p className="empty">No entries for this day yet.</p>}<FoodSuggestions allFoods={allFoods}/></Card>}
const sameMedication=(saved:MedicationDefinition,entry:MedicationEntry)=>entry.medicationId?saved.id===entry.medicationId:saved.name.trim().toLocaleLowerCase()===entry.name.trim().toLocaleLowerCase()&&saved.dose.trim().toLocaleLowerCase()===entry.dose.trim().toLocaleLowerCase();
function MedicationCard({date,day,saved,pending,run}:{date:string,day?:Day,saved:MedicationDefinition[],pending:BusyActions,run:RunAction}){
 const [savedName,setSavedName]=useState(""),[savedDose,setSavedDose]=useState(""),[oneTimeName,setOneTimeName]=useState(""),[oneTimeDose,setOneTimeDose]=useState(""),[oneTimeTime,setOneTimeTime]=useState(localTime);
 const entries=day?.medications??[];
 const usedEntryIds=new Set<string>();
 const checklist=saved.map(medication=>{const taken=entries.find(entry=>!usedEntryIds.has(entry.id)&&sameMedication(medication,entry));if(taken)usedEntryIds.add(taken.id);return {medication,taken}});
 const oneTimeEntries=entries.filter(entry=>!usedEntryIds.has(entry.id));
 const toggle=(medication:MedicationDefinition,taken?:MedicationEntry)=>{const operation=`medication-${medication.id}`;if(taken){run(operation,()=>request("/api/medication",{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({date,id:taken.id})}));return}run(operation,()=>request("/api/medication",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({date,medicationId:medication.id,name:medication.name,dose:medication.dose,time:currentTime()})}))};
 const editMedTime=(id:string,currentTime:string)=>{const newTime=window.prompt("Time taken",currentTime);if(newTime===null||newTime===currentTime)return;run(`edit-med-${id}`,()=>request("/api/medication",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({date,id,time:newTime})}))};
 const pickOneTimeName=(name:string)=>{setOneTimeName(name);const match=saved.find(medication=>medication.name.toLocaleLowerCase()===name.toLocaleLowerCase());if(match)setOneTimeDose(match.dose)};
 return <Card title="Medication" number="03" note="Tap once when taken — the time is saved automatically">
  <section className="medicationChecklist" aria-label="Saved medication checklist">
   <div className="medicationSectionHead"><div><h3>Today&apos;s list</h3><p>Your past medicines stay here so you do not have to retype them.</p></div></div>
   {checklist.length?checklist.map(({medication,taken})=><div className={`savedMedication ${taken?"taken":""}`} key={medication.id}>
    <label className="medicationCheck"><input type="checkbox" checked={!!taken} disabled={pending.has(`medication-${medication.id}`)} onChange={()=>toggle(medication,taken)}/><span><b>{medication.name}</b><small>{medication.dose||"No dose or notes saved"}</small>{taken&&<small className="medicationTakenTime">✓ Taken at {taken.time} <button type="button" className="editMedTime" onClick={e=>{e.preventDefault();editMedTime(taken.id,taken.time)}} aria-label={`Change time for ${medication.name}`}>✎</button></small>}</span></label>
    <button type="button" className="forgetMedication" aria-label={`Remove ${medication.name} from saved medications`} disabled={pending.has(`forget-medication-${medication.id}`)} onClick={()=>window.confirm(`Remove ${medication.name} from your saved list? Past taken records will stay.`)&&run(`forget-medication-${medication.id}`,()=>request("/api/medication-list",{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:medication.id})}))}>Remove</button>
   </div>):<p className="empty medicationEmpty">Add your regular medicine below. Past medication records are also added to this list automatically.</p>}
  </section>
  <details className="medicationAdder"><summary>＋ Add medicine to my saved list</summary><form className="medicationForm" onSubmit={event=>{event.preventDefault();run("medication-list",async()=>{await request("/api/medication-list",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:savedName,dose:savedDose})});setSavedName("");setSavedDose("")})}}><label>Medication name<input value={savedName} onChange={event=>setSavedName(event.target.value)} placeholder="Full medication name" required/></label><label>Usual dose / notes<input value={savedDose} onChange={event=>setSavedDose(event.target.value)} placeholder="e.g. 10 mg with food"/></label><button className="primary" disabled={pending.has("medication-list")}>{pending.has("medication-list")?"Saving…":"Save to my list"}</button></form></details>
  <details className="medicationAdder"><summary>＋ Record a one-time medicine</summary><form className="medicationForm oneTimeMedication" onSubmit={event=>{event.preventDefault();run("medication-once",async()=>{await request("/api/medication",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({date,name:oneTimeName,dose:oneTimeDose,time:oneTimeTime})});setOneTimeName("");setOneTimeDose("");setOneTimeTime(currentTime())})}}><label>Medication<input list="saved-medication-names" value={oneTimeName} onChange={event=>pickOneTimeName(event.target.value)} placeholder="e.g. flu medicine" required/><datalist id="saved-medication-names">{saved.map(medication=><option key={medication.id} value={medication.name}/>)}</datalist></label><label>Dose / notes<input value={oneTimeDose} onChange={event=>setOneTimeDose(event.target.value)} placeholder="Optional"/></label><label>Time<input type="time" value={oneTimeTime} onChange={event=>setOneTimeTime(event.target.value)} required/></label><button className="primary" disabled={pending.has("medication-once")}>{pending.has("medication-once")?"Saving…":"Record one-time medicine"}</button></form></details>
  {oneTimeEntries.length>0&&<div className="entries medicationEntries"><h3>Other medicine taken today</h3>{oneTimeEntries.map(entry=><div key={entry.id}><span><b>{entry.name}</b><small>Taken at {entry.time}{entry.dose?` · ${entry.dose}`:""}</small></span><button onClick={()=>editMedTime(entry.id,entry.time)} aria-label={`Change time for ${entry.name}`}>✎</button><button onClick={()=>window.confirm(`Delete ${entry.name}?`)&&run(`delete-medication-${entry.id}`,()=>request("/api/medication",{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({date,id:entry.id})}))} aria-label={`Delete ${entry.name}`}>×</button></div>)}</div>}
 </Card>
}
function ActivityCard({date,day,busy,run,unitMode}:{date:string,day?:Day,busy:string,run:(n:string,f:()=>Promise<unknown>)=>void,unitMode:UnitMode}){
 const [text,setText]=useState(""),[time,setTime]=useState(localTime),[images,setImages]=useState<File[]>([]);const add=(files:File[])=>setImages(current=>[...current,...files.filter(file=>file.type.startsWith("image/"))]);
 const entries=day?.activities.map(x=>{const legacyHr=x.metRationale?.match(/HR cross-check: ([\d.]+) bpm/)?.[1];const hr=x.averageHeartRateBpm??(legacyHr?Number(legacyHr):null);const blended=x.energySource==="met_hr_blend"&&x.met!=null&&x.heartRateMet!=null;const finalMet=blended?(x.met!+x.heartRateMet!)/2:x.met;const method=x.energySource==="displayed"?"Tracker energy":blended?"50/50 MET + HR":"Table estimate";const hrInfo=blended?` · Heart-rate estimate: ${x.heartRateMet!.toFixed(2)} MET (bounded) · Final: ${finalMet!.toFixed(2)} MET using 50% table and 50% heart rate`:hr?` · Average HR: ${Math.round(hr)} bpm${x.energySource==="displayed"?"":" (not blended below 100 bpm)"}`:"";return{id:x.id,title:x.name,detail:`${x.time?`${x.time} · `:""}${x.durationMinutes?`${Math.round(x.durationMinutes)} min`:x.duration}${finalMet?` · ${finalMet.toFixed(2)} MET`:""}${hr?` · ${method} · ${Math.round(hr)} bpm avg`:x.energySource==="displayed"?` · ${method}`:""}`,time:x.time??"",info:`${x.duration}${x.baseMet?` · Base: ${x.baseMet} MET`:""}${x.adjustmentPercent!=null?` · Context adjustment: ${x.adjustmentPercent>=0?"+":""}${x.adjustmentPercent}%`:""}${x.met?` · Table-adjusted: ${x.met.toFixed(2)} MET`:""}${hrInfo}${x.energySource==="displayed"?" · Tracker-displayed active energy used as-is":""}${x.compendiumCode?` · Compendium code: ${x.compendiumCode}`:""}${x.metRationale?` · ${x.metRationale}`:""}`,value:x.activeEnergy}})??[];
 return <Card title="Activity" number="04" note="Text, tracker screenshots, or photos; net energy above rest"><form onSubmit={e=>{e.preventDefault();run("activity",async()=>{const form=new FormData();form.set("date",date);form.set("time",time);form.set("text",text);await appendUploadImages(form,images);await request("/api/activity",{method:"POST",body:form});setText("");setImages([])})}}><label>Activity time<input type="time" value={time} onChange={e=>setTime(e.target.value)}/></label><textarea value={text} onChange={e=>setText(e.target.value)} onPaste={e=>add([...e.clipboardData.files])} placeholder="Describe activity, or paste a tracker screenshot here…"/><label className="upload">＋ Add activity photos or screenshots<input hidden multiple type="file" accept="image/jpeg,image/png,image/webp,image/gif" onChange={e=>add([...e.target.files??[]])}/></label>{images.length>0&&<div className="previews">{images.map((file,i)=><figure key={i}><img src={URL.createObjectURL(file)} alt="Activity preview"/><button type="button" onClick={()=>setImages(current=>current.filter((_,index)=>index!==i))}>×</button></figure>)}</div>}<button className="primary" disabled={busy==="activity"}>{busy==="activity"?"Analyzing…":"Analyze activity →"}</button></form><Entries entries={entries} edit={(id,currentTime)=>changeEntryDateTime("/api/activity",date,id,currentTime,run)} del={id=>run("delete",()=>request("/api/activity",{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({date,id})}))} unitMode={unitMode}/></Card>
}
function changeEntryDateTime(url:string,date:string,id:string,time:string,run:(n:string,f:()=>Promise<unknown>)=>void){const newDate=window.prompt("Date",date);if(newDate===null)return;const newTime=window.prompt("Time",time);if(newTime===null)return;run("edit",()=>request(url,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({date,id,newDate,time:newTime})}))}
function Entries({entries,edit,del,unitMode}:{entries:{id:string,title:string,detail:string,time:string,info?:string,value:number}[],edit?:(id:string,time:string)=>void,del:(id:string)=>void,unitMode:UnitMode}){return entries.length?<div className="entries">{entries.map(x=><div key={x.id}><span><b>{x.title}</b><small>{x.detail}</small></span><strong>{fmt(x.value,false,unitMode)}</strong>{x.info&&<details className="entryInfo"><summary aria-label={`Calculation details for ${x.title}`}>i</summary><p>{x.info}</p></details>}{edit&&<button onClick={()=>edit(x.id,x.time)} aria-label={`Change date and time for ${x.title}`}>✎</button>}<button onClick={()=>window.confirm(`Delete ${x.title}?`)&&del(x.id)} aria-label={`Delete ${x.title}`}>×</button></div>)}</div>:<p className="empty">No entries for this day yet.</p>}
function Card({title,number,note,children}:{title:string,number:string,note:string,children:React.ReactNode}){return <article className="card"><div className="cardhead"><span>{number}</span><div><h2>{title}</h2><small>{note}</small></div></div>{children}</article>}
function BurnCard({date,day,metrics,busy,run,unitMode}:{date:string,day?:Day,metrics:ReturnType<typeof dayMetrics>,busy:string,run:(n:string,f:()=>Promise<unknown>)=>void,unitMode:UnitMode}){const [raw,setRaw]=useState(day?.trackerBurn?.toString()??""),[factor,setFactor]=useState(day?.correctionFactor??1),[pos,setPos]=useState(day?.rulerPosition??.5);useEffect(()=>{setRaw(day?.trackerBurn?.toString()??"");setFactor(day?.correctionFactor??1);setPos(day?.rulerPosition??.5)},[date,day?.trackerBurn,day?.correctionFactor,day?.rulerPosition]);const save=(next=pos)=>run("burn",()=>request("/api/day",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({date,trackerBurn:raw===""?null:+raw,correctionFactor:factor,rulerPosition:next})}));return <Card title="Burn blend" number="04" note="Choose how the estimates meet"><div className="burnInputs"><label>Raw tracker burn <span>{unitMode==="kcal"?"kcal":"g TNT"}</span><input type="number" min="0" value={raw} onChange={e=>setRaw(e.target.value)}/></label><label>Correction factor<input type="number" min="0" max="5" step=".01" value={factor} onChange={e=>setFactor(+e.target.value)}/></label><button onClick={()=>save()} disabled={busy==="burn"}>Save tracker</button></div><div className="burnBreakdown"><span><small>ESTIMATED RMR</small><b>{fmt(metrics.rmr,false,unitMode)}</b></span><span><small>MINIMAL NON-WALKING ALLOWANCE (20%)</small><b>{fmt(metrics.baselineAllowance,false,unitMode)}</b></span><span><small>MINIMAL DAILY BASELINE</small><b>{fmt(metrics.baselineBurn,false,unitMode)}</b></span><span><small>LOGGED NET ACTIVITY</small><b>{fmt(metrics.activity,false,unitMode)}</b></span></div><p className="baselineNote">Includes a conservative allowance for food thermogenesis and unavoidable stationary-day movement such as posture, personal care, and fidgeting. Excludes deliberate walking, chores, commuting, and exercise.</p><div className="ruler"><div className="ends"><span><small>TRACKER</small><b>{fmt(metrics.tracker,false,unitMode)}</b></span><span><small>AI ESTIMATE: BASELINE + ACTIVITY</small><b>{fmt(metrics.aiBurn,false,unitMode)}</b></span></div><input aria-label="Burn blend position" type="range" min="0" max="100" value={Math.round(pos*100)} onChange={e=>setPos(+e.target.value/100)} onPointerUp={()=>save()} onKeyUp={()=>save()}/><div className="ticks">0%<span>{Math.round(pos*100)}% AI</span>100%</div></div>{metrics.blended==null&&<p className="incomplete">Add a profile, weight logs, and tracker burn to calculate a blend.</p>}</Card>}
function Chart({data,unitMode}:{data:{date:string,intake:number,burn:number|null,estimated:boolean}[],unitMode:UnitMode}){return <article className="card chart"><div className="cardhead"><span>05</span><div><h2>30-day rhythm</h2><small>Intake compared with blended burn; gray is estimated</small></div></div><div className="legend"><i/> Food intake <i/> Blended burn</div>{data.length===0?<p className="empty">No recorded days in this period.</p>:<ResponsiveContainer width="100%" height={280}><BarChart data={data} margin={{top:15,right:8,left:-18,bottom:0}}><CartesianGrid stroke="#dce5d3" vertical={false}/><XAxis dataKey="date" tick={{fontSize:11}}/><YAxis tick={{fontSize:11}}/><Tooltip formatter={v=>v==null?"Missing":fmt(Number(v),false,unitMode)} /><Bar dataKey="intake" fill="#a8c83b" radius={[3,3,0,0]}/><Bar dataKey="burn" radius={[3,3,0,0]}>{data.map((x,i)=><Cell key={i} fill={x.estimated?"#aeb5b1":"#167d72"}/>)}</Bar></BarChart></ResponsiveContainer>}</article>}
function BalanceChart({data,unitMode}:{data:{date:string,balance:number|null,estimated:boolean}[],unitMode:UnitMode}){return <article className="card chart"><div className="cardhead"><span>06</span><div><h2>30-day surplus / deficit</h2><small>Food intake minus blended burn; gray is estimated</small></div></div>{data.length===0?<p className="empty">No recorded days in this period.</p>:<ResponsiveContainer width="100%" height={280}><BarChart data={data} margin={{top:15,right:8,left:-18,bottom:0}}><CartesianGrid stroke="#dce5d3" vertical={false}/><XAxis dataKey="date" tick={{fontSize:11}}/><YAxis tick={{fontSize:11}} domain={[(min:number)=>Math.min(min,0),(max:number)=>Math.max(max,0)]} allowDecimals={false} tickFormatter={v=>Math.round(Number(v)).toLocaleString()}/><Tooltip formatter={v=>v==null?"Missing":fmt(Number(v),true,unitMode)} /><ReferenceLine y={0} stroke="#18342d"/><Bar dataKey="balance" name="Surplus / deficit" radius={[3,3,0,0]}>{data.map((x,i)=><Cell key={i} fill={x.estimated?"#aeb5b1":"#5d8379"}/>)}</Bar></BarChart></ResponsiveContainer>}</article>}
function WeightChart({data}:{data:{date:string,daily:number|null,average:number|null}[]}){return <article className="card chart"><div className="cardhead"><span>05</span><div><h2>30-day weight</h2><small>Daily average and trailing seven-day exponential moving average</small></div></div>{data.length===0?<p className="empty">No weight recorded in this period.</p>:<ResponsiveContainer width="100%" height={280}><LineChart data={data} margin={{top:15,right:16,left:-8,bottom:0}}><CartesianGrid stroke="#dce5d3" vertical={false}/><XAxis dataKey="date" tick={{fontSize:11}}/><YAxis tick={{fontSize:11}} domain={["auto","auto"]}/><Tooltip formatter={(value,name)=>[`${Number(value).toFixed(2)} kg`,name==="daily"?"Daily average":"7-day exponential average"]}/><Line type="linear" dataKey="daily" name="daily" stroke="#a8c83b" strokeWidth={2} connectNulls={false}/><Line type="linear" dataKey="average" name="average" stroke="#167d72" strokeWidth={3} connectNulls/></LineChart></ResponsiveContainer>}</article>}
function EnergyTable({metrics:m,unitMode}:{metrics:ReturnType<typeof dayMetrics>,unitMode:UnitMode}){
 const columns=[m.intake,m.baselineBurn,m.activity,m.tracker,m.blended,m.balance];
 const primaryRows=unitMode==="kcal"?[{unit:"kcal",value:(n:number)=>Math.round(n).toLocaleString()}]:[{unit:"g TNT",value:(n:number)=>Math.round(n).toLocaleString()},{unit:"g C4",value:(n:number)=>Math.round(n/C4_TNT_FACTOR).toLocaleString()}];
 const rows=[...primaryRows,{unit:"kWh",value:(n:number)=>(n*KCAL_TO_KWH).toLocaleString(undefined,{maximumFractionDigits:3})},{unit:"TeV",value:(n:number)=>(n*2.611447e10).toExponential(3)},{unit:"8×B200 Hour",value:(n:number)=>(n*KCAL_TO_KWH/8).toLocaleString(undefined,{maximumFractionDigits:3})},{unit:"k tokens",value:(n:number)=>Math.round(n*KCAL_TO_KWH*315).toLocaleString()},{unit:"Sun power × seconds",value:(n:number)=>(n*KCAL_TO_JOULES/3.828e26).toExponential(3)},{unit:"BOE",value:(n:number)=>(n*KCAL_TO_JOULES/6.1178632e9).toExponential(3)},{unit:"GC–MS × Hour",value:(n:number)=>(n*KCAL_TO_KWH/4.05).toLocaleString(undefined,{maximumFractionDigits:3})},{unit:"g fat equivalent",value:(n:number)=>(n/7.7).toLocaleString(undefined,{maximumFractionDigits:1})},{unit:"iPhone 15 full charges",value:(n:number)=>(n*KCAL_TO_KWH*1000/12.98).toLocaleString(undefined,{maximumFractionDigits:1})}];
 const energy=m.blended??m.aiBurn??m.intake;
 const [facts,setFacts]=useState<string[]>([]),[factError,setFactError]=useState(""),[loadingFacts,setLoadingFacts]=useState(false);
 useEffect(()=>{setFacts([]);setFactError("")},[energy]);
 const generate=async()=>{if(energy<=0)return;setLoadingFacts(true);setFactError("");try{const result=await request<{facts:string[]}>("/api/fun-facts",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({energyKcal:energy})});setFacts(result.facts)}catch(error){setFactError(error instanceof Error?error.message:"Could not generate fun facts")}finally{setLoadingFacts(false)}};
 return <article className="card energyTable"><div className="cardhead"><span>07</span><div><h2>Selected-day energy conversions</h2><small>The same energy balance across many scales and units</small></div></div><div className="tableScroll"><table><thead><tr><th>Unit</th><th>Food intake</th><th>Baseline burn</th><th>Active movement</th><th>Corrected tracker</th><th>Blended burn</th><th>Surplus / deficit</th></tr></thead><tbody>{rows.map(row=><tr key={row.unit}><th>{row.unit}</th>{columns.map((n,i)=><td key={i}>{n==null?"—":row.value(n)}</td>)}</tr>)}</tbody></table></div><p className="conversionNote">8×B200 Hour uses 8 kW. k tokens are based on Lambda.ai 8×B200 running GLM-5.2 at 700 tokens/s across 32 concurrent requests: 2,520 k tokens per 8 kWh (315 k tokens/kWh). GC–MS × Hour assumes an Agilent 8890 GC (2.95 kW maximum continuous) plus 5977-series MSD (1.10 kW), totaling 4.05 kW. g fat equivalent uses the planning approximation 7.7 food kilocalories/g and is not a guarantee of scale-weight change. iPhone 15 full charges use a 12.98 Wh rated battery and ignore charging losses. Sun power uses 3.828 × 10²⁶ W. One BOE uses 6.1178632 GJ.</p><div className="funFacts"><div><h3>What could this energy do?</h3><p>Ask GPT-5.6 Luna for playful comparisons based on the selected day&apos;s burn.</p></div><button onClick={generate} disabled={loadingFacts||energy<=0}>{loadingFacts?"Generating…":"Generate fun facts"}</button>{factError&&<p className="factError" role="alert">{factError}</p>}{facts.length>0&&<ul>{facts.map((fact,i)=><li key={i}>{fact}</li>)}</ul>}</div></article>
}
