"use client";
import {useCallback,useEffect,useMemo,useState} from "react";
import {Bar,BarChart,CartesianGrid,ReferenceLine,ResponsiveContainer,Tooltip,XAxis,YAxis} from "recharts";
import {dayMetrics} from "@/lib/calc";import type {Day,Profile,State} from "@/lib/types";
const localDate=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`};
const localTime=()=>{const d=new Date();return `${String(d.getHours()).padStart(2,"0")}:${String(d.getMinutes()).padStart(2,"0")}`};
const C4_TNT_FACTOR=1.34;
const fmt=(n:number|null,signed=false)=>{if(n==null)return "—";const prefix=signed&&n>=0?"+":"";const tnt=Math.round(n).toLocaleString();const c4=Math.round(n/C4_TNT_FACTOR).toLocaleString();return `${prefix}${tnt} g TNT\n${prefix}${c4} g C4`};
async function request(url:string,init?:RequestInit){const r=await fetch(url,init);const b=await r.json();if(!r.ok)throw new Error(b.error||"Request failed");return b}
export default function Home(){
 const [state,setState]=useState<State>({profile:null,days:{}}),[date,setDate]=useState(localDate),[error,setError]=useState(""),[busy,setBusy]=useState("");
 const load=useCallback(()=>request("/api/state").then(setState).catch(e=>setError(e.message)),[]);useEffect(()=>{load()},[load]);
 const day=state.days[date];const m=dayMetrics(state.profile,day);
 const chart=useMemo(()=>{const out=[];const base=new Date(date+"T12:00:00");for(let i=29;i>=0;i--){const x=new Date(base);x.setDate(x.getDate()-i);const key=`${x.getFullYear()}-${String(x.getMonth()+1).padStart(2,"0")}-${String(x.getDate()).padStart(2,"0")}`;const day=state.days[key];const mm=dayMetrics(state.profile,day);out.push({date:key.slice(5),intake:mm.intake,burn:mm.blended,balance:mm.balance,recorded:!!day&&(day.foods.length>0||day.activities.length>0||day.trackerBurn!=null)})}const first=out.findIndex(x=>x.recorded);return first<0?[]:out.slice(first)},[date,state]);
 async function run(name:string,fn:()=>Promise<unknown>){setBusy(name);setError("");try{await fn();await load()}catch(e){setError(e instanceof Error?e.message:"Something went wrong")}finally{setBusy("")}}
 return <main><header><div><span className="eyebrow">DAILY ENERGY LEDGER</span><h1>Fuel <i>&</i> Motion</h1><p>One unit. A clearer picture of what comes in and what moves out.</p></div><label className="date">Selected day<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label></header>
 {error&&<div className="error" role="alert">{error}<button onClick={()=>setError("")}>×</button></div>}
 <section className="metrics">
  <Metric label="Food intake" value={fmt(m.intake)} tone="lime"/><Metric label="Baseline daily burn" value={fmt(m.baselineBurn)} sub="RMR + 10% allowance"/><Metric label="Active movement" value={fmt(m.activity)} sub="Above baseline"/>
  <Metric label="Corrected tracker" value={fmt(m.tracker)} sub={day?.trackerBurn!=null?`${day.trackerBurn} × ${day.correctionFactor}`:"Needs tracker input"}/><Metric label="Blended burn" value={fmt(m.blended)} tone="teal"/><Metric label={m.balance!=null&&m.balance<0?"Deficit":"Surplus / deficit"} value={fmt(m.balance,true)} tone={m.balance!=null&&m.balance>0?"warm":"blue"}/>
 </section>
 <section className="grid"><div className="stack"><ProfileCard profile={state.profile} busy={busy} save={p=>run("profile",()=>request("/api/profile",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(p)}))}/><FoodCard date={date} day={day} busy={busy} run={run}/><MedicationCard date={date} day={day} busy={busy} run={run}/><ActivityCard date={date} day={day} busy={busy} run={run}/></div>
 <div className="stack"><BurnCard date={date} day={day} metrics={m} busy={busy} run={run}/><Chart data={chart}/><BalanceChart data={chart}/></div></section>
 </main>
}
function Metric({label,value,sub,tone=""}:{label:string,value:string,sub?:string,tone?:string}){return <article className={`metric ${tone}`}><small>{label}</small><strong>{value}</strong>{sub&&<span>{sub}</span>}</article>}
function ProfileCard({profile,busy,save}:{profile:Profile|null,busy:string,save:(p:Profile)=>void}){const [p,setP]=useState<Profile>(profile??{sex:"female",age:30,heightCm:165,weightKg:65});useEffect(()=>{if(profile)setP(profile)},[profile]);return <Card title="Your baseline" number="01" note="Used for every date"><form className="form profile" onSubmit={e=>{e.preventDefault();save(p)}}><label>Biological sex<select value={p.sex} onChange={e=>setP({...p,sex:e.target.value as Profile["sex"]})}><option value="female">Female</option><option value="male">Male</option></select></label><label>Age<input type="number" min="13" max="120" value={p.age} onChange={e=>setP({...p,age:+e.target.value})}/></label><label>Height <span>cm</span><input type="number" value={p.heightCm} onChange={e=>setP({...p,heightCm:+e.target.value})}/></label><label>Weight <span>kg</span><input type="number" step=".1" value={p.weightKg} onChange={e=>setP({...p,weightKg:+e.target.value})}/></label><button disabled={busy==="profile"}>{busy==="profile"?"Saving…":"Save profile"}</button></form></Card>}
function FoodCard({date,day,busy,run}:{date:string,day?:Day,busy:string,run:(n:string,f:()=>Promise<unknown>)=>void}){const [text,setText]=useState(""),[time,setTime]=useState(localTime),[images,setImages]=useState<File[]>([]);const add=(files:File[])=>setImages(v=>[...v,...files.filter(f=>f.type.startsWith("image/"))]);return <Card title="Food intake" number="02" note="Text, photos, or both"><form onSubmit={e=>{e.preventDefault();run("food",async()=>{const f=new FormData();f.set("date",date);f.set("time",time);f.set("text",text);images.forEach(x=>f.append("images",x));await request("/api/food",{method:"POST",body:f});setText("");setImages([])})}}><label>Meal time<input type="time" value={time} onChange={e=>setTime(e.target.value)} required/></label><textarea value={text} onChange={e=>setText(e.target.value)} onPaste={e=>add([...e.clipboardData.files])} placeholder="Describe your meal, or paste an image here…"/><label className="upload">＋ Add food photos<input hidden multiple type="file" accept="image/jpeg,image/png,image/webp,image/gif" onChange={e=>add([...e.target.files??[]])}/></label>{images.length>0&&<div className="previews">{images.map((f,i)=><figure key={i}><img src={URL.createObjectURL(f)} alt="Food preview"/><button type="button" onClick={()=>setImages(x=>x.filter((_,j)=>j!==i))}>×</button></figure>)}</div>}<button className="primary" disabled={busy==="food"}>{busy==="food"?"Analyzing…":"Analyze food →"}</button></form><Entries entries={day?.foods.map(x=>({id:x.id,title:x.name,detail:`${x.time?`${x.time} · `:""}${x.amount}`,value:x.energy}))??[]} del={id=>run("delete",()=>request("/api/food",{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({date,id})}))}/></Card>}
function MedicationCard({date,day,busy,run}:{date:string,day?:Day,busy:string,run:(n:string,f:()=>Promise<unknown>)=>void}){const [name,setName]=useState(""),[dose,setDose]=useState(""),[time,setTime]=useState(localTime);const meds=day?.medications??[];return <Card title="Medication" number="03" note="Separate daily medication log"><form className="medicationForm" onSubmit={e=>{e.preventDefault();run("medication",async()=>{await request("/api/medication",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({date,name,dose,time})});setName("");setDose("")})}}><label>Medication<input value={name} onChange={e=>setName(e.target.value)} placeholder="Medication name" required/></label><label>Dose / notes<input value={dose} onChange={e=>setDose(e.target.value)} placeholder="e.g. 10 mg with food" required/></label><label>Time<input type="time" value={time} onChange={e=>setTime(e.target.value)} required/></label><button className="primary" disabled={busy==="medication"}>{busy==="medication"?"Saving…":"Record medication"}</button></form>{meds.length?<div className="entries medicationEntries">{meds.map(x=><div key={x.id}><span><b>{x.name}</b><small>{x.time} · {x.dose}</small></span><button onClick={()=>run("delete",()=>request("/api/medication",{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({date,id:x.id})}))} aria-label={`Delete ${x.name}`}>×</button></div>)}</div>:<p className="empty">No medications recorded for this day.</p>}</Card>}
function ActivityCard({date,day,busy,run}:{date:string,day?:Day,busy:string,run:(n:string,f:()=>Promise<unknown>)=>void}){const [text,setText]=useState("");return <Card title="Activity" number="04" note="Active energy above rest"><form onSubmit={e=>{e.preventDefault();run("activity",async()=>{await request("/api/activity",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({date,text})});setText("")})}}><textarea value={text} onChange={e=>setText(e.target.value)} placeholder="e.g. 45 min brisk walk and 20 min yoga"/><button className="primary" disabled={busy==="activity"}>{busy==="activity"?"Analyzing…":"Analyze activity →"}</button></form><Entries entries={day?.activities.map(x=>({id:x.id,title:x.name,detail:`${x.durationMinutes?`${Math.round(x.durationMinutes)} min`:x.duration}${x.met?` · ${x.met.toFixed(2)} MET`:""}`,info:`${x.duration}${x.baseMet?` · Base: ${x.baseMet} MET`:""}${x.adjustmentPercent!=null?` · Adjustment: ${x.adjustmentPercent>=0?"+":""}${x.adjustmentPercent}%`:""}${x.met?` · Adjusted: ${x.met.toFixed(2)} MET`:""}${x.compendiumCode?` · Compendium code: ${x.compendiumCode}`:""}${x.metRationale?` · ${x.metRationale}`:""}`,value:x.activeEnergy}))??[]} del={id=>run("delete",()=>request("/api/activity",{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({date,id})}))}/></Card>}
function Entries({entries,del}:{entries:{id:string,title:string,detail:string,info?:string,value:number}[],del:(id:string)=>void}){return entries.length?<div className="entries">{entries.map(x=><div key={x.id}><span><b>{x.title}</b><small>{x.detail}</small></span><strong>{fmt(x.value)}</strong>{x.info&&<details className="entryInfo"><summary aria-label={`Calculation details for ${x.title}`}>i</summary><p>{x.info}</p></details>}<button onClick={()=>del(x.id)} aria-label={`Delete ${x.title}`}>×</button></div>)}</div>:<p className="empty">No entries for this day yet.</p>}
function Card({title,number,note,children}:{title:string,number:string,note:string,children:React.ReactNode}){return <article className="card"><div className="cardhead"><span>{number}</span><div><h2>{title}</h2><small>{note}</small></div></div>{children}</article>}
function BurnCard({date,day,metrics,busy,run}:{date:string,day?:Day,metrics:ReturnType<typeof dayMetrics>,busy:string,run:(n:string,f:()=>Promise<unknown>)=>void}){const [raw,setRaw]=useState(day?.trackerBurn?.toString()??""),[factor,setFactor]=useState(day?.correctionFactor??1),[pos,setPos]=useState(day?.rulerPosition??.5);useEffect(()=>{setRaw(day?.trackerBurn?.toString()??"");setFactor(day?.correctionFactor??1);setPos(day?.rulerPosition??.5)},[date,day?.trackerBurn,day?.correctionFactor,day?.rulerPosition]);const save=(next=pos)=>run("burn",()=>request("/api/day",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({date,trackerBurn:raw===""?null:+raw,correctionFactor:factor,rulerPosition:next})}));return <Card title="Burn blend" number="04" note="Choose how the estimates meet"><div className="burnInputs"><label>Raw tracker burn <span>g TNT</span><input type="number" min="0" value={raw} onChange={e=>setRaw(e.target.value)}/></label><label>Correction factor<input type="number" min="0" max="5" step=".01" value={factor} onChange={e=>setFactor(+e.target.value)}/></label><button onClick={()=>save()} disabled={busy==="burn"}>Save tracker</button></div><div className="burnBreakdown"><span><small>ESTIMATED RMR</small><b>{fmt(metrics.rmr)}</b></span><span><small>10% SEDENTARY / FOOD ALLOWANCE</small><b>{fmt(metrics.baselineAllowance)}</b></span><span><small>BASELINE DAILY BURN</small><b>{fmt(metrics.baselineBurn)}</b></span><span><small>LOGGED NET ACTIVITY</small><b>{fmt(metrics.activity)}</b></span></div><div className="ruler"><div className="ends"><span><small>TRACKER</small><b>{fmt(metrics.tracker)}</b></span><span><small>AI ESTIMATE: BASELINE + ACTIVITY</small><b>{fmt(metrics.aiBurn)}</b></span></div><input aria-label="Burn blend position" type="range" min="0" max="100" value={Math.round(pos*100)} onChange={e=>setPos(+e.target.value/100)} onPointerUp={()=>save()} onKeyUp={()=>save()}/><div className="ticks">0%<span>{Math.round(pos*100)}% AI</span>100%</div></div>{metrics.blended==null&&<p className="incomplete">Add a profile and tracker burn to calculate a blend.</p>}</Card>}
function Chart({data}:{data:{date:string,intake:number,burn:number|null}[]}){return <article className="card chart"><div className="cardhead"><span>05</span><div><h2>30-day rhythm</h2><small>Intake compared with blended burn</small></div></div><div className="legend"><i/> Food intake <i/> Blended burn</div>{data.length===0?<p className="empty">No recorded days in this period.</p>:<ResponsiveContainer width="100%" height={280}><BarChart data={data} margin={{top:15,right:8,left:-18,bottom:0}}><CartesianGrid stroke="#dce5d3" vertical={false}/><XAxis dataKey="date" tick={{fontSize:11}}/><YAxis tick={{fontSize:11}}/><Tooltip formatter={v=>v==null?"Missing":fmt(Number(v))} /><Bar dataKey="intake" fill="#a8c83b" radius={[3,3,0,0]}/><Bar dataKey="burn" fill="#167d72" radius={[3,3,0,0]}/></BarChart></ResponsiveContainer>}</article>}
function BalanceChart({data}:{data:{date:string,balance:number|null}[]}){return <article className="card chart"><div className="cardhead"><span>06</span><div><h2>30-day surplus / deficit</h2><small>Food intake minus blended burn</small></div></div>{data.length===0?<p className="empty">No recorded days in this period.</p>:<ResponsiveContainer width="100%" height={280}><BarChart data={data} margin={{top:15,right:8,left:-18,bottom:0}}><CartesianGrid stroke="#dce5d3" vertical={false}/><XAxis dataKey="date" tick={{fontSize:11}}/><YAxis tick={{fontSize:11}} domain={[(min:number)=>Math.min(min,0),(max:number)=>Math.max(max,0)]} allowDecimals={false} tickFormatter={v=>Math.round(Number(v)).toLocaleString()}/><Tooltip formatter={v=>v==null?"Missing":fmt(Number(v),true)} /><ReferenceLine y={0} stroke="#18342d"/><Bar dataKey="balance" name="Surplus / deficit" fill="#5d8379" radius={[3,3,0,0]}/></BarChart></ResponsiveContainer>}</article>}
